import fs from "node:fs/promises";
import path from "node:path";

import {
  auditableModels,
  triggerBackedModels,
  type AuditMetadata,
} from "../metadata.js";
import { generateAuditSchema } from "../generator/index.js";
import { generateTriggerSql } from "../generator/triggers.js";
import { rebaseRelativePaths } from "../generator/rebase.js";
import { parseSchemaFile } from "../parser/index.js";

export interface GenerateCommandOptions {
  /** The annotated schema the developer edits. */
  schema: string;
  /** Directory the Prisma-ready schema is written to. */
  outDir: string;
  /**
   * Treat every `[Auditable]` model as `[AuditTriggers]` as well.
   *
   * A shorthand for a schema where every audited model should be enforced in
   * the database, so the annotation does not have to be repeated forty times.
   * The metadata and the SQL are written from this one decision in this one
   * command, which is what keeps the two from disagreeing.
   */
  triggers?: boolean;
}

export interface GenerateCommandResult {
  metadata: AuditMetadata;
  warnings: string[];
  written: string[];
}

/**
 * Turn the annotated `schema.prisma` into everything Prisma needs:
 *
 *     prisma/schema.prisma          <- source of truth, has [Auditable]
 *     prisma/.audit/schema.prisma   <- same schema, annotations stripped
 *     prisma/.audit/audit.prisma    <- Revision + *Aud models
 *     prisma/.audit/audit.metadata.json
 *
 * Prisma is pointed at the `.audit` directory, which it reads as a multi-file
 * schema, so `prisma migrate` and `prisma generate` see one coherent schema.
 */
export async function runGenerate(
  options: GenerateCommandOptions,
): Promise<GenerateCommandResult> {
  const schemaPath = path.resolve(options.schema);
  const outDir = path.resolve(options.outDir);
  const schemaDir = path.dirname(schemaPath);

  const { cleanSchema, metadata, warnings } = await parseSchemaFile(schemaPath);

  if (options.triggers) {
    for (const model of auditableModels(metadata)) model.triggers = true;
  }

  await fs.mkdir(outDir, { recursive: true });

  const cleanPath = path.join(outDir, "schema.prisma");
  const auditPath = path.join(outDir, "audit.prisma");
  const metadataPath = path.join(outDir, "audit.metadata.json");

  const header =
    "// Generated by prisma-audit from " +
    `${path.relative(outDir, schemaPath).split(path.sep).join("/")}. Do not edit.\n`;

  await fs.writeFile(
    cleanPath,
    header + rebaseRelativePaths(cleanSchema, schemaDir, outDir),
    "utf8",
  );
  await fs.writeFile(auditPath, generateAuditSchema(metadata), "utf8");
  await fs.writeFile(metadataPath, `${JSON.stringify(metadata, null, 2)}\n`, "utf8");

  const written = [cleanPath, auditPath, metadataPath];

  // A copy for inspection and diffing. The one that actually runs is the one
  // committed under prisma/migrations, since this directory is generated and
  // git-ignored — `prisma-audit triggers` is what writes that one.
  if (triggerBackedModels(metadata).length > 0) {
    const triggersPath = path.join(outDir, "audit.triggers.sql");
    await fs.writeFile(triggersPath, generateTriggerSql(metadata), "utf8");
    written.push(triggersPath);
  }

  return { metadata, warnings, written };
}

/** A one-line summary of what was generated, for CLI output. */
export function describeResult(result: GenerateCommandResult): string {
  const models = auditableModels(result.metadata);

  if (models.length === 0) {
    return "No [Auditable] models found.";
  }

  return models
    .map((model) => {
      const audited = model.fields.filter((field) => field.audited).length;
      const skipped = model.fields.length - audited;
      const suffix = skipped > 0 ? `, ${skipped} field(s) excluded` : "";
      const enforced = model.triggers ? ", trigger" : "";
      return `  ${model.name} -> ${model.auditModelName} (${audited} column(s)${suffix}${enforced})`;
    })
    .join("\n");
}
