-- CreateTable
CREATE TABLE "payment_aud" (
    "revisionId" BIGINT NOT NULL,
    "revType" "RevisionType" NOT NULL,
    "id" INTEGER NOT NULL,
    "order_id" INTEGER,
    "amount" DECIMAL(12,2),
    "status" TEXT,

    CONSTRAINT "payment_aud_pkey" PRIMARY KEY ("revisionId","id")
);

-- CreateTable
CREATE TABLE "payment" (
    "id" SERIAL NOT NULL,
    "order_id" INTEGER NOT NULL,
    "amount" DECIMAL(12,2) NOT NULL,
    "status" TEXT NOT NULL,

    CONSTRAINT "payment_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "payment_aud_id_revisionId_idx" ON "payment_aud"("id", "revisionId");

-- CreateIndex
CREATE INDEX "payment_aud_revisionId_idx" ON "payment_aud"("revisionId");

-- AddForeignKey
ALTER TABLE "payment_aud" ADD CONSTRAINT "payment_aud_revisionId_fkey" FOREIGN KEY ("revisionId") REFERENCES "revision"("id") ON DELETE CASCADE ON UPDATE CASCADE;
-- ---------------------------------------------------------------------------
-- Generated by prisma-audit. Do not edit.
-- Re-create with `prisma-audit triggers` and apply it as a migration.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION "prisma_audit_revision"() RETURNS bigint
LANGUAGE plpgsql AS $prisma_audit$
DECLARE
  revision_id bigint;
BEGIN
  -- An unset setting reads as NULL, and one reverted at the end of an earlier
  -- transaction reads as the empty string. Both mean "not published".
  revision_id := nullif(current_setting('prisma_audit.revision_id', true), '')::bigint;
  IF revision_id IS NOT NULL THEN
    RETURN revision_id;
  END IF;

  INSERT INTO "revision" ("userId", "username")
  VALUES (
    nullif(current_setting('prisma_audit.user_id', true), ''),
    nullif(current_setting('prisma_audit.username', true), '')
  )
  RETURNING "id" INTO revision_id;

  PERFORM set_config('prisma_audit.revision_id', revision_id::text, true);

  RETURN revision_id;
END;
$prisma_audit$;

-- Payment -> payment_aud
CREATE OR REPLACE FUNCTION "prisma_audit_payment_aud"() RETURNS trigger
LANGUAGE plpgsql AS $prisma_audit$
DECLARE
  revision_id bigint;
  row_state   record;
  rev_type    "RevisionType";
BEGIN
  -- The runtime says so while it is writing the audit rows itself, which is
  -- what lets the triggers be installed before the build that relies on them.
  IF nullif(current_setting('prisma_audit.suppress', true), '') = 'on' THEN
    RETURN NULL;
  END IF;

  IF TG_OP = 'DELETE' THEN
    row_state := OLD;  -- after a delete there is no NEW left to read
    rev_type  := 'DELETE';
  ELSIF TG_OP = 'UPDATE' THEN
    row_state := NEW;
    rev_type  := 'UPDATE';
  ELSE
    row_state := NEW;
    rev_type  := 'INSERT';
  END IF;

  revision_id := "prisma_audit_revision"();

  INSERT INTO "payment_aud" (
    "revisionId", "revType", "id", "order_id", "amount", "status"
  )
  VALUES (
    revision_id, rev_type, row_state."id", row_state."order_id", row_state."amount", row_state."status"
  )
  -- A row touched twice in one revision keeps one audit record, holding the
  -- state it ended up in. Created and then changed stays an INSERT: that is
  -- what the revision did to it.
  ON CONFLICT ("revisionId", "id") DO UPDATE SET
    "revType" = CASE
                  WHEN "payment_aud"."revType" = 'INSERT'
                   AND excluded."revType" = 'UPDATE'
                  THEN 'INSERT'::"RevisionType"
                  ELSE excluded."revType"
                END,
    "order_id" = excluded."order_id",
    "amount" = excluded."amount",
    "status" = excluded."status";

  RETURN NULL;
END;
$prisma_audit$;

DROP TRIGGER IF EXISTS "prisma_audit" ON "payment";
CREATE TRIGGER "prisma_audit"
AFTER INSERT OR UPDATE OR DELETE ON "payment"
FOR EACH ROW EXECUTE FUNCTION "prisma_audit_payment_aud"();

-- Whatever an earlier version of this file installed and this one does not.
DO $prisma_audit$
DECLARE
  stale record;
BEGIN
  FOR stale IN
    SELECT c.relname AS name
    FROM pg_trigger g
    JOIN pg_class c     ON c.oid = g.tgrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE g.tgname = 'prisma_audit'
      AND NOT g.tgisinternal
      AND n.nspname = current_schema()
      AND c.relname <> ALL (ARRAY['payment']::text[])
  LOOP
    EXECUTE format('DROP TRIGGER %I ON %I', 'prisma_audit', stale.name);
  END LOOP;

  FOR stale IN
    SELECT p.proname AS name
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = current_schema()
      AND p.proname LIKE 'prisma\_audit\_%'
      AND p.pronargs = 0
      AND p.proname <> ALL (ARRAY['prisma_audit_revision', 'prisma_audit_payment_aud']::text[])
  LOOP
    EXECUTE format('DROP FUNCTION %I()', stale.name);
  END LOOP;
END
$prisma_audit$;
