import { stripAuditAttributes } from "./attributes.js";
import {
  auditableModels,
  auditedFields,
  type AuditField,
  type AuditMetadata,
  type AuditModel,
} from "../metadata.js";

const BANNER = [
  "// ---------------------------------------------------------------------------",
  "// Generated by prisma-audit. Do not edit.",
  "// Edit prisma/schema.prisma and re-run `prisma-audit generate` instead.",
  "// ---------------------------------------------------------------------------",
];

export interface GenerateOptions {
  /**
   * Emit `@@index([<pk>, revisionId])` on each audit model. This is the index
   * behind every `atRevision` lookup, so it is on by default.
   */
  indexes?: boolean;
}

/** Build the contents of `audit.prisma` from parsed schema metadata. */
export function generateAuditSchema(
  metadata: AuditMetadata,
  options: GenerateOptions = {},
): string {
  const models = auditableModels(metadata);
  const withIndexes = options.indexes ?? true;

  const out: string[] = [...BANNER, ""];

  out.push("enum RevisionType {", "  INSERT", "  UPDATE", "  DELETE", "}", "");

  out.push(...revisionModel(models));

  for (const model of models) {
    out.push(...auditModel(model, withIndexes));
  }

  return `${out.join("\n").trimEnd()}\n`;
}

/**
 * The central revision table, Envers' `REVINFO`.
 *
 * It carries no `type` column on purpose: one revision is one transaction and
 * may contain an INSERT, an UPDATE and a DELETE at the same time, so the
 * operation belongs on the audit row rather than on the revision.
 */
function revisionModel(models: AuditModel[]): string[] {
  const out = [
    "model Revision {",
    "  id        BigInt   @id @default(autoincrement())",
    "  timestamp DateTime @default(now())",
    "",
    "  userId   String?",
    "  username String?",
  ];

  if (models.length > 0) {
    out.push("");
    // Prisma requires the back-relation on both sides of a 1:N relation.
    for (const model of models) {
      out.push(`  ${model.auditDelegate} ${model.auditModelName}[]`);
    }
  }

  out.push("", '  @@map("revision")', "}", "");
  return out;
}

function auditModel(model: AuditModel, withIndexes: boolean): string[] {
  const fields = auditedFields(model);
  const primaryKey = model.primaryKey;

  if (!primaryKey) {
    throw new Error(`Model ${model.name} has no primary key to audit against`);
  }

  const out = [
    `model ${model.auditModelName} {`,
    "  revisionId BigInt",
    "  revision   Revision     @relation(fields: [revisionId], references: [id], onDelete: Cascade)",
    "  revType    RevisionType",
    "",
  ];

  const width = Math.max(...fields.map((field) => field.name.length));

  for (const field of fields) {
    const isPrimaryKey = field.name === primaryKey;
    out.push(`  ${field.name.padEnd(width)} ${auditColumnType(field, isPrimaryKey)}`);
  }

  out.push("");
  out.push(`  @@id([revisionId, ${primaryKey}])`);

  if (withIndexes) {
    // The hot path is `WHERE <pk> = ? AND revision_id <= ? ORDER BY revision_id DESC`,
    // which this composite index serves directly.
    out.push(`  @@index([${primaryKey}, revisionId])`);
    out.push("  @@index([revisionId])");
  }

  out.push(`  @@map("${model.auditTableName}")`, "}", "");
  return out;
}

/**
 * Render an audit column: the source type with identity and default attributes
 * stripped.
 *
 * Non-key columns are always emitted as optional, because a column added to the
 * source model later has no value in the revisions recorded before it existed.
 * The primary key stays required — it is part of `@@id([revisionId, <pk>])`,
 * and Prisma does not allow an optional field in a composite id.
 */
function auditColumnType(field: AuditField, isPrimaryKey: boolean): string {
  const kept = stripAuditAttributes(field.attributes);

  const type = isPrimaryKey ? field.type : `${field.type}?`;
  return kept ? `${type} ${kept}` : type;
}
