import {
  auditedFields,
  columnNameOf,
  tableNameOf,
  triggerBackedModels,
  type AuditMetadata,
  type AuditModel,
} from "../metadata.js";
import {
  SETTING_REVISION_ID,
  SETTING_SUPPRESS,
  SETTING_USER_ID,
  SETTING_USERNAME,
  SUPPRESS_ON,
} from "../util/settings.js";
import {
  MAX_IDENTIFIER_LENGTH,
  quoteIdentifier,
  quoteLiteral,
  textArray,
} from "../util/sql.js";

/**
 * The trigger every audited table carries, named the same on each one.
 *
 * A constant name is what makes `DROP TRIGGER IF EXISTS` a reliable handle:
 * re-running the generated file replaces what an earlier one installed instead
 * of accumulating triggers beside it.
 */
export const TRIGGER_NAME = "prisma_audit";

/** Every generated function starts with this, which is how the sweep finds them. */
const FUNCTION_PREFIX = "prisma_audit_";

/** The shared function that resolves the revision a transaction records under. */
const REVISION_FUNCTION = `${FUNCTION_PREFIX}revision`;

/**
 * Names the generator in `generator/index.ts` fixes on the Prisma side, repeated
 * here because the SQL has to spell them out rather than go through Prisma.
 */
const REVISION_TABLE = "revision";
const REVISION_TYPE = "RevisionType";

/** The dollar-quote tag every generated body uses. */
const TAG = "$prisma_audit$";

const BANNER = [
  "-- ---------------------------------------------------------------------------",
  "-- Generated by prisma-audit. Do not edit.",
  "-- Re-create with `prisma-audit triggers` and apply it as a migration.",
  "-- ---------------------------------------------------------------------------",
];

export interface TriggerOptions {
  /**
   * Emit the inverse: remove every trigger and function prisma-audit installed,
   * and leave the audit tables and their contents alone.
   */
  drop?: boolean;
}

/** The function that backs the trigger on a model, e.g. `prisma_audit_product_aud`. */
export function triggerFunctionName(model: AuditModel): string {
  return `${FUNCTION_PREFIX}${model.auditTableName}`;
}

/**
 * Build the SQL that installs the audit triggers.
 *
 * The file is idempotent and convergent: everything is `CREATE OR REPLACE` or
 * `DROP … IF EXISTS`, and it closes with a sweep that removes the triggers and
 * functions of models that are no longer trigger-backed. Applying the newest
 * file therefore reaches the same state whatever an earlier one installed,
 * which is what lets a schema change and its trigger update travel in one
 * migration.
 */
export function generateTriggerSql(
  metadata: AuditMetadata,
  options: TriggerOptions = {},
): string {
  const models = options.drop ? [] : triggerBackedModels(metadata);

  if (models.length > 0 && metadata.provider !== "postgresql") {
    throw new Error(
      `Audit triggers are PostgreSQL-only, and the schema declares ${metadata.provider ?? "no"} as its datasource provider.`,
    );
  }

  const out: string[] = [...BANNER, ""];

  if (models.length > 0) {
    out.push(...revisionResolver());
    for (const model of models) out.push(...triggerFor(model));
  }

  out.push(...sweep(models));

  return `${out.join("\n").trimEnd()}\n`;
}

/**
 * The revision a transaction records under.
 *
 * The runtime publishes it before its first write. A write that never went
 * through the runtime — psql, another service, a cascade — finds nothing
 * published, so a revision is opened here and published back, which is what
 * makes every later statement of the same transaction share it. Outside an
 * explicit transaction each statement is its own, and gets its own revision:
 * one unit of work, one revision, either way.
 */
function revisionResolver(): string[] {
  return [
    `CREATE OR REPLACE FUNCTION ${quoteIdentifier(REVISION_FUNCTION)}() RETURNS bigint`,
    `LANGUAGE plpgsql AS ${TAG}`,
    "DECLARE",
    "  revision_id bigint;",
    "BEGIN",
    "  -- An unset setting reads as NULL, and one reverted at the end of an earlier",
    "  -- transaction reads as the empty string. Both mean \"not published\".",
    `  revision_id := nullif(current_setting(${quoteLiteral(SETTING_REVISION_ID)}, true), '')::bigint;`,
    "  IF revision_id IS NOT NULL THEN",
    "    RETURN revision_id;",
    "  END IF;",
    "",
    `  INSERT INTO ${quoteIdentifier(REVISION_TABLE)} ("userId", "username")`,
    "  VALUES (",
    `    nullif(current_setting(${quoteLiteral(SETTING_USER_ID)}, true), ''),`,
    `    nullif(current_setting(${quoteLiteral(SETTING_USERNAME)}, true), '')`,
    "  )",
    "  RETURNING \"id\" INTO revision_id;",
    "",
    `  PERFORM set_config(${quoteLiteral(SETTING_REVISION_ID)}, revision_id::text, true);`,
    "",
    "  RETURN revision_id;",
    "END;",
    `${TAG};`,
    "",
  ];
}

/** The function and the trigger that record one model's rows. */
function triggerFor(model: AuditModel): string[] {
  const functionName = triggerFunctionName(model);

  if (functionName.length > MAX_IDENTIFIER_LENGTH) {
    throw new Error(
      `The trigger function for ${model.name} would be called ${functionName}, which is longer than PostgreSQL's ${String(MAX_IDENTIFIER_LENGTH)}-character identifier limit. Give the model a shorter audit table with [AuditTable("...")].`,
    );
  }

  const table = quoteIdentifier(tableNameOf(model));
  const auditTable = quoteIdentifier(model.auditTableName);

  const columns = auditedFields(model).map(columnNameOf);
  const keyColumns = keyColumnsOf(model);
  const keys = new Set(keyColumns);
  // A key column is part of the conflict target and equal by construction, so
  // re-assigning it on conflict would say nothing.
  const copied = columns.filter((column) => !keys.has(column));

  const inserted = ['"revisionId"', '"revType"', ...columns.map(quoteIdentifier)];
  const values = ["revision_id", "rev_type", ...columns.map((column) => `row_state.${quoteIdentifier(column)}`)];

  const assignments = [
    ...revTypeAssignment(auditTable),
    ...copied.map(
      (column, index) =>
        `    ${quoteIdentifier(column)} = excluded.${quoteIdentifier(column)}${index === copied.length - 1 ? ";" : ","}`,
    ),
  ];

  return [
    `-- ${model.name} -> ${model.auditTableName}`,
    `CREATE OR REPLACE FUNCTION ${quoteIdentifier(functionName)}() RETURNS trigger`,
    `LANGUAGE plpgsql AS ${TAG}`,
    "DECLARE",
    "  revision_id bigint;",
    "  row_state   record;",
    `  rev_type    ${quoteIdentifier(REVISION_TYPE)};`,
    "BEGIN",
    "  -- The runtime says so while it is writing the audit rows itself, which is",
    "  -- what lets the triggers be installed before the build that relies on them.",
    `  IF nullif(current_setting(${quoteLiteral(SETTING_SUPPRESS)}, true), '') = ${quoteLiteral(SUPPRESS_ON)} THEN`,
    "    RETURN NULL;",
    "  END IF;",
    "",
    "  IF TG_OP = 'DELETE' THEN",
    "    row_state := OLD;  -- after a delete there is no NEW left to read",
    "    rev_type  := 'DELETE';",
    "  ELSIF TG_OP = 'UPDATE' THEN",
    "    row_state := NEW;",
    "    rev_type  := 'UPDATE';",
    "  ELSE",
    "    row_state := NEW;",
    "    rev_type  := 'INSERT';",
    "  END IF;",
    "",
    `  revision_id := ${quoteIdentifier(REVISION_FUNCTION)}();`,
    "",
    `  INSERT INTO ${auditTable} (`,
    `    ${inserted.join(", ")}`,
    "  )",
    "  VALUES (",
    `    ${values.join(", ")}`,
    "  )",
    "  -- A row touched twice in one revision keeps one audit record, holding the",
    "  -- state it ended up in. Created and then changed stays an INSERT: that is",
    "  -- what the revision did to it.",
    `  ON CONFLICT (${['"revisionId"', ...keyColumns.map(quoteIdentifier)].join(", ")}) DO UPDATE SET`,
    ...assignments,
    "",
    "  RETURN NULL;",
    "END;",
    `${TAG};`,
    "",
    `DROP TRIGGER IF EXISTS ${quoteIdentifier(TRIGGER_NAME)} ON ${table};`,
    `CREATE TRIGGER ${quoteIdentifier(TRIGGER_NAME)}`,
    `AFTER INSERT OR UPDATE OR DELETE ON ${table}`,
    `FOR EACH ROW EXECUTE FUNCTION ${quoteIdentifier(functionName)}();`,
    "",
  ];
}

/**
 * The revision type of an audit row that is written twice in one revision.
 *
 * This is the SQL transcription of the rule the runtime applies in memory: an
 * INSERT followed by an UPDATE is still the revision creating the row.
 */
function revTypeAssignment(auditTable: string): string[] {
  return [
    "    \"revType\" = CASE",
    `                  WHEN ${auditTable}."revType" = 'INSERT'`,
    "                   AND excluded.\"revType\" = 'UPDATE'",
    `                  THEN 'INSERT'::${quoteIdentifier(REVISION_TYPE)}`,
    "                  ELSE excluded.\"revType\"",
    "                END,",
  ];
}

/** The key columns as the database spells them, in key order. */
function keyColumnsOf(model: AuditModel): string[] {
  return model.primaryKey.map((name) => {
    const field = model.fields.find((candidate) => candidate.name === name);
    return field ? columnNameOf(field) : name;
  });
}

/**
 * Remove what should no longer be there.
 *
 * Driven from the catalogue rather than from a record of what an earlier file
 * installed, so it converges no matter which version was applied last — a model
 * that lost `[AuditTriggers]`, lost `[Auditable]`, or was renamed all end up
 * the same way. Triggers go before functions, because a function still in use
 * by a trigger cannot be dropped.
 */
function sweep(models: AuditModel[]): string[] {
  const tables = textArray(models.map(tableNameOf));
  const functions = textArray(
    models.length > 0 ? [REVISION_FUNCTION, ...models.map(triggerFunctionName)] : [],
  );

  return [
    "-- Whatever an earlier version of this file installed and this one does not.",
    `DO ${TAG}`,
    "DECLARE",
    "  stale record;",
    "BEGIN",
    "  FOR stale IN",
    "    SELECT c.relname AS name",
    "    FROM pg_trigger g",
    "    JOIN pg_class c     ON c.oid = g.tgrelid",
    "    JOIN pg_namespace n ON n.oid = c.relnamespace",
    `    WHERE g.tgname = ${quoteLiteral(TRIGGER_NAME)}`,
    "      AND NOT g.tgisinternal",
    "      AND n.nspname = current_schema()",
    `      AND c.relname <> ALL (${tables})`,
    "  LOOP",
    `    EXECUTE format('DROP TRIGGER %I ON %I', ${quoteLiteral(TRIGGER_NAME)}, stale.name);`,
    "  END LOOP;",
    "",
    "  FOR stale IN",
    "    SELECT p.proname AS name",
    "    FROM pg_proc p",
    "    JOIN pg_namespace n ON n.oid = p.pronamespace",
    "    WHERE n.nspname = current_schema()",
    `      AND p.proname LIKE ${quoteLiteral(`${FUNCTION_PREFIX.replace(/_/g, "\\_")}%`)}`,
    "      AND p.pronargs = 0",
    `      AND p.proname <> ALL (${functions})`,
    "  LOOP",
    "    EXECUTE format('DROP FUNCTION %I()', stale.name);",
    "  END LOOP;",
    "END",
    `${TAG};`,
    "",
  ];
}
